

export const ADD_NEW_USER_CONNECTION = 'ADD_NEW_USER_CONNECTION'
export const REMOVE_USER_CONNECTION = 'REMOVE_USER_CONNECTION'


export const ADD_ALL_SCREEN_SHARE_CONNECTIONS = 'ADD_ALL_SCREEN_SHARE_CONNECTIONS'
export const ADD_SCREEN_SHARE_CONNECTION = 'ADD_SCREEN_SHARE_CONNECTION'