


export const VIDEO_MODEL_TOGGLE = 'VIDEO_MODEL_TOGGLE'
export const SHOW_VIDEO_STREAM = 'SHOW_VIDEO_STREAM'

export const GET_VIDEO_CHAT = 'GET_VIDEO_CHAT'
export const VIDEO_CHAT_NOT_FOUND = 'VIDEO_CHAT_NOT_FOUND'