

export const SET_PINNED_STREAM = 'SET_PINNED_STREAM'
export const ADD_RTCP_CONNECTION = 'ADD_RTCP_CONNECTION'
export const REQUEST_FULFILLED = 'REQUEST_FULFILLED'


export const ADD_CONNECTION_MEDIA_STREAM = 'ADD_CONNECTION_MEDIA_STREAM'
export const ADD_SCREEN_CONNECTION_STREAM = 'ADD_SCREEN_CONNECTION_STREAM'